Repository gnosis/ido-ux, pull requests merged in 2021-04, with the labels that each got.

#399 [issue-357] showing site, if only 1 endpoint is up
  src/api/AdditionalServicesApi.ts
Labels: bug, enhancement

#398 [issue-336] Long numbers on the chart overlap
  src/components/auction/Charts/XYChart.ts
Labels: bug

#408 Displaying correct min buy
  src/components/modals/common/PlaceOrderModalFooter/index.tsx
Labels: QA passed

#409 tiny fix in price calcuation function
  src/components/auction/OrderbookWidget/index.tsx
Labels: QA passed

#407 Showing price instead of min price
  src/components/auctions/AuctionInfoCard/index.tsx
Labels: QA passed

#435 [issue-379] xdai gas price is not always set correctly
  src/hooks/useApproveCallback.ts
  src/hooks/useCancelOrderCallback.ts
  src/hooks/useClaimOrderCallback.ts
  src/hooks/useGasPrice.ts
  src/hooks/usePlaceOrderCallback.ts
  src/hooks/useSendCallback.ts
Labels: enhancement

#470 fix: Always allows a user to connect with wallet connect
  src/components/modals/WalletModal/index.tsx
Labels: high priority

#471 Does not allow to place orders below the clearing price
  src/components/auction/OrderPlacement/index.tsx
  src/state/orderPlacement/hooks.ts
Labels: high priority

#480 (Fix) Waiting modal appears when clicking on the Claim button again
  src/components/auction/Claimer/index.tsx
  src/components/auction/OrderPlacement/index.tsx
  src/hooks/useClaimOrderCallback.ts
  src/state/orderPlacement/hooks.ts
Labels: Merge After Sale, QA passed
